services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/exmanage
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: elemmire13
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - backend_network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: exmanage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: elemmire13
    ports:
      - "5432:5432"
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
